# ===============================
# LOCAL CONFIGURATION
# ===============================

# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/shopdb

# User and password
spring.datasource.username=root
spring.datasource.password=root

# Driver JDBC of MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
